import 'package:flutter/material.dart';

// JOURNAL SCREEN
//Icon: A journal or notebook icon.
//Function: Allows users to view past journal entries, including transcripts and insights generated by Gemini.
//Label: "Journal".

class JournalScreen extends StatefulWidget {
  const JournalScreen({super.key});

  @override
  State<JournalScreen> createState() => _JournalScreenState();
}

class _JournalScreenState extends State<JournalScreen> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
        body: Center(
      child: Text('Journal Screen'),
    ));
  }
}
